
baseURL = 'https://antimaterie.ro/'
title = 'Antimaterie'
theme = "PaperMod"
defaultContentLanguage = 'ro'
defaultContentLanguageInSubdir = true

# Automatically generate robots.txt
enableRobotsTXT = true
showTableOfContents = true
	
	paginate = 10
	enableInlineShortcodes = true
	buildDrafts = false
	buildFuture = false
	buildExpired = false
	enableEmoji = true
	pygmentsUseClasses = true
	mainsections = [ "arhive", "distilat", "flux", "papermod" ]

	[minify]
	disableXML = true
	
[languages]
	[languages.ro]
	languageCode = 'ro-RO'
	contentDir = "content"
	weight = 1
	disabled = false
	languageDirection = 'ltr'
	languageName = 'Română'
	  [languages.ro.taxonomies]
#	  category = "categorii"
#	  tag = "tags"
#	  series = "serii"
#      fluxes = "flux"
	  
	[languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    weight = 2
    [languages.en.params]
      subtitle = 'English version'

	[[languages.ro.menu.main]]
	name = "Distilat"
	url = "distilat/"
	weight = 2

	[[languages.ro.menu.main]]
	name = "Flux"
	url = "flux/"
	weight = 1

	[[languages.ro.menu.main]]
	name = "Tags"
	url = "tags/"
	weight = 10

	[[languages.ro.menu.main]]
	name = "Arhive"
	url = "archives/"
	weight = 15

	[outputs]
	home = [ "HTML", "RSS", "JSON" ]

    [taxonomies]
      author = 'authors'
      tag = "tags"
      category = "categories"

[services]
  [services.googleAnalytics]
    id = 'G-YCEPNKDC74'

	[params]
	env = "production"
	description = "Antimaterie"
	defaultTheme = "auto"
	ShowShareButtons = true
	ShowReadingTime = true
	displayFullLangName = false
	ShowPostNavLinks = true
	ShowBreadCrumbs = false
	ShowCodeCopyButtons = true
	ShowRssButtonInSectionTermList = true
	ShowAllPagesInArchive = true
	ShowPageNums = true
	ShowToc = true
	images = [ "images/papermod-cover.png" ]

	  [params.profileMode]
	  enabled = false
	  title = "PaperMod"
	  imageUrl = "#"
	  imageTitle = "my image"

	    [[params.profileMode.buttons]]
	    name = "Archives"
	    url = "archives"

	    [[params.profileMode.buttons]]
	    name = "Tags"
	    url = "tags"

	  [params.homeInfoParams]
	  Title = "Ce e Antimaterie, de ce și pentru cine?"
	  Content = """Antimaterie e un blog colectiv care dă o voce celor care au altă poziție decât ceea ce devine pe zi ce trece dogma obligatorie a unei entități tehnocratice oligarhice care distruge democrația în numele salvării ei. El e gândit pentru a fi ușor de citit și ușor de actualizat de fiecare contributor în parte. E construit pe o platformă fiabilă și rapidă și găzduit distribuit."""


	  [[params.socialIcons]]
	  name = "Discord"
	  title = "Comentează pe Discord"
	  url = "https://discord.gg/59aqgQ5a"


#	  [params.editPost]
#	  URL = "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
#	  Text = "Suggest Changes"
#	  appendFilePath = true

	  [params.assets]
	  disableHLJS = true



	[markup.goldmark.renderer]
	unsafe = true

	[markup.highlight]
	noClasses = false

	[services.instagram]
	disableInlineCSS = true

	[services.twitter]
	disableInlineCSS = true
	
