baseURL = 'https://antimaterie.ro/'
languageCode = 'en-us'
title = 'Antimaterie'

theme = "PaperMod"

# Automatically generate robots.txt
enableRobotsTXT = true

showTableOfContents = true
	
	
	
	
	paginate = 5
	enableInlineShortcodes = true
	buildDrafts = false
	buildFuture = false
	buildExpired = false
	enableEmoji = true
	pygmentsUseClasses = true
	mainsections = [ "posts", "papermod" ]

	[minify]
	disableXML = true

	[languages.en]
	languageName = "English"
	weight = 1

	  [languages.en.taxonomies]
	  category = "categories"
	  tag = "tags"
	  series = "series"

	[[languages.en.menu.main]]
	name = "Blog"
	url = "blog"
	weight = 5

	[[languages.en.menu.main]]
	name = "Posts"
	url = "posts/"
	weight = 10

	[[languages.en.menu.main]]
	name = "Tags"
	url = "tags/"
	weight = 10


	[outputs]
	home = [ "HTML", "RSS", "JSON" ]

	[params]
	env = "production"
	description = "Antimaterie"
	author = "Florin Cojocariu"
	defaultTheme = "auto"
	ShowShareButtons = true
	ShowReadingTime = true
	displayFullLangName = true
	ShowPostNavLinks = true
	ShowBreadCrumbs = true
	ShowCodeCopyButtons = true
	ShowRssButtonInSectionTermList = true
	ShowAllPagesInArchive = true
	ShowPageNums = true
	ShowToc = true
	images = [ "images/papermod-cover.png" ]

	  [params.profileMode]
	  enabled = false
	  title = "PaperMod"
	  imageUrl = "#"
	  imageTitle = "my image"

	    [[params.profileMode.buttons]]
	    name = "Archives"
	    url = "archives"

	    [[params.profileMode.buttons]]
	    name = "Tags"
	    url = "tags"

	  [params.homeInfoParams]
	  Title = "Ce e Antimaterie, de ce și pentru cine?"
	  Content = """
	Antimaterie e un blog colectiv care dă o voce celor care au altă poziție decât ceea ce devine pe zi ce trece dogma obligatorie a unei entități tehnocratice oligarhice care distruge democrația în numele salvării ei. El e gândit pentru a fi ușor de citit și ușor de actualizat de fiecare contributor în parte. E construit pe o platformă fiabilă și rapidă și găzduit distribuit.
	
	Textele scrise apar într-un stream continuu și decizia publicării lor revine exclusiv autorilor. Pentru actualizări, vă puteți abona la un newsletter sau la un flux rss. Accesul în 2024 e liber.
	

	  [[params.socialIcons]]
	  name = "Discord"
	  title = "comunitatea antimaterie pe Discord"
	  url = "https://discord.gg/usMJptYA"


	  [params.editPost]
	  URL = "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
	  Text = "Suggest Changes"
	  appendFilePath = true

	  [params.assets]
	  disableHLJS = true

	[markup.goldmark.renderer]
	unsafe = true

	[markup.highlight]
	noClasses = false

	[services.instagram]
	disableInlineCSS = true

	[services.twitter]
	disableInlineCSS = true
	